trigger:
  branches:
    include:
      - master
  paths:
    include:
      - backend/**
      - frontend/**
      - azure-pipelines.yml
      - gitversion.yml

variables:
  - group: 'build args'
  - group: 'dockerhub'

pool:
  name: 'SelfHosted'

stages:
  - stage: build_and_push
    displayName: Build & Push
    jobs:

######### BACKEND #########
      - job: backend
        displayName: Backend image
        steps:
          - checkout: self
            fetchDepth: 0

            # Gitversion
          - task: gitversion-setup@4
            displayName: GitVersion setup
            inputs:
              versionSpec: '6.3.0'

          - task: gitversion-execute@4
            displayName: GitVersion execute
            inputs:
              configFilePath: 'gitversion.yml'
              

          # docker hub login
          - task: Docker@2
            inputs:
              containerRegistry: 'DockerHub'
              command: 'login'

          # build docker image (backend)
          - bash: |
              set -euo pipefail
              echo "Building BACKEND $(GitVersion.SemVer)"
              docker build \
                --build-arg BACKEND_VERSION=$(GitVersion.SemVer) \
                -t $(DOCKERHUB_NAMESPACE)/$(BACKEND_REPO):$(GitVersion.SemVer) \
                -t $(DOCKERHUB_NAMESPACE)/$(BACKEND_REPO):latest \
                backend
            displayName: Docker build (backend)

          # push to hub
          - bash: |
              set -euo pipefail
              echo "Pushing BACKEND image ($(GitVersion.SemVer), latest)"
              docker push $(DOCKERHUB_NAMESPACE)/$(BACKEND_REPO):$(GitVersion.SemVer)
              docker push $(DOCKERHUB_NAMESPACE)/$(BACKEND_REPO):latest
            displayName: Docker push (backend)

######### FRONTEND #########
      - job: frontend
        displayName: Frontend image
        steps:
          - checkout: self
            fetchDepth: 0

          - task: gitversion-setup@4
            displayName: GitVersion setup
            inputs:
              versionSpec: '6.3.0'

          - task: gitversion-execute@4
            displayName: GitVersion execute
            inputs:
              configFilePath: 'gitversion.yml'

          # check REACT_APP_API_BASE_URL var
          - bash: |
              set -euo pipefail
              : "${REACT_APP_API_BASE_URL:?REACT_APP_API_BASE_URL is required}"
              echo "REACT_APP_API_BASE_URL=$(REACT_APP_API_BASE_URL)"
            displayName: Validate frontend build args

          - task: Docker@2
            inputs:
              containerRegistry: 'DockerHub'
              command: 'login'

          # build frontend with args
          - bash: |
              set -euo pipefail
              echo "Building FRONTEND image..."
              docker build \
                --build-arg REACT_APP_VERSION=$(GitVersion.SemVer) \
                --build-arg REACT_APP_API_BASE_URL=$(REACT_APP_API_BASE_URL) \
                -t $(DOCKERHUB_NAMESPACE)/$(FRONTEND_REPO):$(GitVersion.SemVer) \
                -t $(DOCKERHUB_NAMESPACE)/$(FRONTEND_REPO):latest \
                frontend
            displayName: Docker build (frontend)

          - bash: |
              set -euo pipefail
              echo "Pushing FRONTEND image ($(GitVersion.SemVer), latest)"
              docker push $(DOCKERHUB_NAMESPACE)/$(FRONTEND_REPO):$(GitVersion.SemVer)
              docker push $(DOCKERHUB_NAMESPACE)/$(FRONTEND_REPO):latest
            displayName: Docker push (frontend)


