trigger:
  branches:
    include:
      - master
  paths:
    include:
      - backend/**
      - frontend/**
      - azure-pipelines.yml

variables:
  - group: 'build args'
  - group: 'dockerhub-creds'

pool:
  name: 'SelfHosted'

stages:
  - stage: build_and_push
    displayName: Build & Push
    jobs:

      # backend
      - job: backend
        displayName: Backend image
        steps:
          - checkout: self
            fetchDepth: 0

          # check varibles
          - bash: |
              set -euo pipefail
              : "${APP_VERSION:?APP_VERSION is required}"
              echo "APP_VERSION=$(APP_VERSION)"
            displayName: Validate backend version

          # docker hub login
          - task: Docker@2
            inputs:
              containerRegistry: 'DockerHub'
              command: 'login'

          # build docker image (backend)
          - bash: |
              set -euo pipefail
              echo "Building BACKEND image..."
              docker build \
                --build-arg BACKEND_VERSION=$(BACKEND_VERSION) \
                -t $(DOCKERHUB_NAMESPACE)/$(BACKEND_REPO):$(BACKEND_VERSION) \
                -t $(DOCKERHUB_NAMESPACE)/$(BACKEND_REPO):latest \
                backend
            displayName: Docker build (backend)

          # push to hub
          - bash: |
              set -euo pipefail
              echo "Pushing BACKEND image (v$(BACKEND_VERSION), latest)"
              docker push $(DOCKERHUB_NAMESPACE)/$(BACKEND_REPO):$(BACKEND_VERSION)
              docker push $(DOCKERHUB_NAMESPACE)/$(BACKEND_REPO):latest
            displayName: Docker push (backend)

      # frontend
      - job: frontend
        displayName: Frontend image
        steps:
          - checkout: self
            fetchDepth: 0

          # check varibles
          - bash: |
              set -euo pipefail
              : "${REACT_APP_VERSION:?REACT_APP_VERSION is required}"
              : "${REACT_APP_API_BASE_URL:?REACT_APP_API_BASE_URL is required}"
              echo "REACT_APP_VERSION=$(REACT_APP_VERSION)"
              echo "REACT_APP_API_BASE_URL=$(REACT_APP_API_BASE_URL)"
            displayName: Validate frontend build args
            env:
              REACT_APP_VERSION: $(REACT_APP_VERSION)
              REACT_APP_API_BASE_URL: $(REACT_APP_API_BASE_URL)

          - task: Docker@2
            inputs:
              containerRegistry: 'DockerHub'
              command: 'login'

          # build frontend with args
          - bash: |
              set -euo pipefail
              echo "Building FRONTEND image..."
              docker build \
                --build-arg REACT_APP_VERSION=$(REACT_APP_VERSION) \
                --build-arg REACT_APP_API_BASE_URL=$(REACT_APP_API_BASE_URL) \
                -t $(DOCKERHUB_NAMESPACE)/$(FRONTEND_REPO):$(REACT_APP_VERSION) \
                -t $(DOCKERHUB_NAMESPACE)/$(FRONTEND_REPO):latest \
                frontend
            displayName: Docker build (frontend)

          - bash: |
              set -euo pipefail
              echo "Pushing FRONTEND image (v..., latest)"
              docker push $(DOCKERHUB_NAMESPACE)/$(FRONTEND_REPO):$(REACT_APP_VERSION)
              docker push $(DOCKERHUB_NAMESPACE)/$(FRONTEND_REPO):latest
            displayName: Docker push (frontend)
