apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-backend-svc"
spec:
  selector:
    app: "{{ .Release.Name }}-backend" # pod label
  ports:
    - protocol: TCP
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}
  type: ClusterIP