"""add test column to todos

Revision ID: 92a7b246f4df
Revises: 036d2986ef8e
Create Date: 2025-06-27 17:57:57.164811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92a7b246f4df'
down_revision: Union[str, Sequence[str], None] = '036d2986ef8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('test', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'test')
    # ### end Alembic commands ###
