- name: Update packages and install Docker
  hosts: all
  become: true

  tasks:
  - name: update all packages
    dnf:
      name: '*'
      state: latest


  - name: set docker repo 
    # не нашел модуль, использую shell
    shell: dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    
  - name: install docker and packages
    dnf:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
      state: present

  - name: start and enable docker systemd
    systemd:
      name: docker
      state: started
      enabled: true

  - name: add current user to docker group
    user:
      name: "{{ ansible_user }}"
      groups: docker
      append: true
