apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: pool1
  namespace: metallb-system
spec:
  addresses:
    - 192.168.99.240-192.168.99.245
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2adv1
  namespace: metallb-system
spec:
  ipAddressPools:
    - pool1