/* tslint:disable */
/* eslint-disable */
/**
 * To-Do List API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BodyUpdateCompletedStatusTodosTodoIdPatch
 */
export interface BodyUpdateCompletedStatusTodosTodoIdPatch {
    /**
     * 
     * @type {boolean}
     * @memberof BodyUpdateCompletedStatusTodosTodoIdPatch
     */
    completed: boolean;
}

/**
 * Check if a given object implements the BodyUpdateCompletedStatusTodosTodoIdPatch interface.
 */
export function instanceOfBodyUpdateCompletedStatusTodosTodoIdPatch(value: object): value is BodyUpdateCompletedStatusTodosTodoIdPatch {
    if (!('completed' in value) || value['completed'] === undefined) return false;
    return true;
}

export function BodyUpdateCompletedStatusTodosTodoIdPatchFromJSON(json: any): BodyUpdateCompletedStatusTodosTodoIdPatch {
    return BodyUpdateCompletedStatusTodosTodoIdPatchFromJSONTyped(json, false);
}

export function BodyUpdateCompletedStatusTodosTodoIdPatchFromJSONTyped(json: any, ignoreDiscriminator: boolean): BodyUpdateCompletedStatusTodosTodoIdPatch {
    if (json == null) {
        return json;
    }
    return {
        
        'completed': json['completed'],
    };
}

export function BodyUpdateCompletedStatusTodosTodoIdPatchToJSON(json: any): BodyUpdateCompletedStatusTodosTodoIdPatch {
    return BodyUpdateCompletedStatusTodosTodoIdPatchToJSONTyped(json, false);
}

export function BodyUpdateCompletedStatusTodosTodoIdPatchToJSONTyped(value?: BodyUpdateCompletedStatusTodosTodoIdPatch | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'completed': value['completed'],
    };
}

