/* tslint:disable */
/* eslint-disable */
/**
 * To-Do List API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TodoCreate
 */
export interface TodoCreate {
    /**
     * 
     * @type {string}
     * @memberof TodoCreate
     */
    title: string;
    /**
     * 
     * @type {boolean}
     * @memberof TodoCreate
     */
    completed?: boolean;
}

/**
 * Check if a given object implements the TodoCreate interface.
 */
export function instanceOfTodoCreate(value: object): value is TodoCreate {
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function TodoCreateFromJSON(json: any): TodoCreate {
    return TodoCreateFromJSONTyped(json, false);
}

export function TodoCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): TodoCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'completed': json['completed'] == null ? undefined : json['completed'],
    };
}

export function TodoCreateToJSON(json: any): TodoCreate {
    return TodoCreateToJSONTyped(json, false);
}

export function TodoCreateToJSONTyped(value?: TodoCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'completed': value['completed'],
    };
}

