global:
  enabled: true
  tlsDisable: true 

server:
  ha:
    enabled: false
    raft:
      enabled: true
      setNodeId: true
      config: |
        ui = true
        listener "tcp" {
          address         = "[::]:8200"
          cluster_address = "[::]:8201"
          tls_disable     = true
        }
        storage "raft" {
          path = "/vault/data"
        }
        service_registration "kubernetes" {}

  dataStorage:
    enabled: true
    size: 5Gi

  auditStorage:
    enabled: false

  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"